### ISSUE TITLE
DIY ESPHome не прокидывается в хаб

### ISSUE THREAD

**Issue by top4ek** [sprut/Hub#1049]
** Подробное описание ошибки **
Пытаюсь завести двое часов с BLE по [вики](https://wiki.sprut.ai/ru/spruthub/accessory/MQTT_esphome_esp32_ble_gateway) подглядывая в [инструкцию](https://spruthub.ru/news/diy-ustroystva-mqtt-integrirovannye-v-sprut-hub/). MQTT контроллер пуст. 
![Screenshot_20220131_205556](https://user-images.githubusercontent.com/16016/151847152-abc62587-3a84-4217-a208-2384d3ec045e.png)

** Как воспроизвести ? **
1. Создать контроллер MQTT, локальный(т.е. порт 44444)
2. В соответствии с инструкциями добавить поддержку MQTT в ESPHpme
```
mqtt:
  broker: 192.168.1.7
  port: 44444
  discovery: false
  topic_prefix: spruthub-sensors
```
3. Переименовать сущности температуры, влажности, батарейки в соответствии с маном и выставить retain
```
sensor:
  - platform: xiaomi_lywsd02
    mac_address: "xx:xx:xx:xx:xx:xx"
    temperature:
      name: "LYWSD02 Hall clock temperature"
      retain: true
    humidity:
      name: "LYWSD02 Hall clock humidity"
      retain: true
    battery_level:
      name: "LYWSD02 Hall clock battery Level"
      retain: true
```
4. Залить прошивку, подождать пока перехватятся новые данные.
![Screenshot_20220131_193337](https://user-images.githubusercontent.com/16016/151845819-61b8b22a-d19e-43bf-a844-7c067fb3017c.png)
5. Нажать кнопку поиска новых устройств в старом интерфейсе и/или подождать. 

** Ожидаемое поведение **
Наличие устройства в MQTT контроллере.

** Пожалуйста, заполните следующую информацию: **
  - Версия: CE 6567
